# Site settings
title: TenTen Blog
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: tenten
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
markdown: kramdown
kramdown:
  input: GFM

highlight: rouge
